### ISSUE TITLE
Requested present mode mailbox is not in the list

### ISSUE THREAD

**Issue by junglie85** [BVE-Reborn/rend3#437]
I get the following error when trying to run the `cube-no-framework` example from commit [1fc492e](https://github.com/BVE-Reborn/rend3/commit/1fc492eedd9deebca80063a3985ff057d57f776a):

```
     Running `target\debug\cube-no-framework.exe`
thread 'main' panicked at 'Error in Surface::configure: requested present mode Mailbox is not in the list of supported present modes: [Immediate, Fifo]', C:\Users\junglie85\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:281:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\cube-no-framework.exe` (exit code: 101)
```

**Comment by setzer22** [comment]
Thanks for reporting!

This probably broke during the update to latest wgpu, where the way PresentMode works changed and Mailbox no longer gracefully degrades to Fifo.

**Comment by setzer22** [comment]
@junglie85  This should be fixed by #439. Could you please give it a try to confirm it also works on your end? :+1:

**Comment by junglie85** [comment]
@setzer22 sorry for the slow reply, I've been away for most of the last month.

With the latest main branch, the example opens a window then closes with the following output:

```
cargo run --bin cube-no-framework
   Compiling rend3-cube-no-framework-example v0.3.0 (D:\rend3\examples\cube-no-framework)
    Finished dev [unoptimized + debuginfo] target(s) in 19.23s
     Running `target\debug\cube-no-framework.exe`
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 163.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 163.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 163.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 163.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 163.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 163.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 492.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 492.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 492.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 492.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 492.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
[ERROR wgpu_hal::vulkan::instance] VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (0x6bbb14)]
        Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x2d273f60d30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: [VUID-StandaloneSpirv-Flat-06202] OpEntryPoint interfaces variable must not be vertex execution model with an input storage class for Entry Point id 492.
      %object_idx = OpVariable %_ptr_Input_uint Input

[ERROR wgpu_hal::vulkan::instance]      objects: (type: DEVICE, hndl: 0x2d273f60d30, name: ?)
thread 'main' panicked at 'Error in Surface::configure: requested present mode Mailbox is not in the list of supported present modes: [Immediate, Fifo]', C:\Users\junglie85\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.13.1\src\backend\direct.rs:281:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\cube-no-framework.exe` (exit code: 101)
```

The example still has `Mailbox` in main.rs on line 191 but if I change that to `Fifo` then it works (with all the errors still).

**Comment by setzer22** [comment]
Ah, good catch! I forgot it was set in two different places. I approved the PR :+1:
